name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.OBLAK_BOT_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install NPM dependencies
        run: npm install
      - name: Release
        env:
          GIT_AUTHOR_NAME: "oblakbot"
          GIT_AUTHOR_EMAIL: "sibin.grasic+bot@oblak.studio"
          GIT_COMMITTER_NAME: "oblakbot"
          GIT_COMMITTER_EMAIL: "sibin.grasic+bot@oblak.studio"
          GITHUB_TOKEN: ${{ secrets.OBLAK_BOT_TOKEN }}
        run: npm run semantic-release
